export enum techs {
  JavaScript = "JavaScript",
  TypeScript = "TypeScript",
  CSS = "CSS",
  HTML = "HTML",
  NodeJS = "NodeJS",
  NextJS = "NextJS",
  Remix = "Remix",
  MySQL = "MySQL",
  PostgreSQL = "PostgreSQL",
  MongoDB = "MongoDB",
  React = "React",
  TailwindCSS = "TailwindCSS",
  Babel = "Babel",
  Prisma = "Prisma",
  ExpressJS = "ExpressJS",
  Cypress = "Cypress",
  AWS = "AWS",
  GCS = "Google Cloud Services",
  Flightcontrol = "Flightcontrol",
  Render = "Render",
  BlitzJS = "BlitzJS",
  Docker = "Docker",
  NGINX = "NGINX",
  StoryBook = "StoryBook",
  StoryBlok = "StoryBlok (CMS)",
  GitHub = "GitHub",
  Git = "Git",
  Husky = "Husky",
  CICD = "CI/CD",
  CPP = "C++",
  Python = "Python",
  CS = "C#",
  DotNet = ".NET Framework",
  PICKIT3 = "PICKIT 3",
  C = "C",
  Azure = "Azure",
  SQL = "SQL",
  Java = "Java",
  SystemVerilog = "SystemVerilog",
  MATLAB = "MATLAB",
  OrCAD = "OrCAD",
  Allegro = "Allegro",
  QuartusPrime = "Quartus Prime",
  RadxaRockPi = "Radxa Rock Pi",
  Figma = "Figma",
  ModelSim = "ModelSim",
  FPGA = "FPGA",
  Arduino = "Arduino",
  Vercel = "Vercel",
}

export const experienceTech = [
  techs.JavaScript,
  techs.TypeScript,
  techs.CSS,
  techs.HTML,
  techs.NodeJS,
  techs.Remix,
  techs.PostgreSQL,
  techs.React,
  techs.TailwindCSS,
  techs.Babel,
  techs.Prisma,
  techs.ExpressJS,
  techs.Cypress,
  techs.AWS,
  techs.GCS,
  techs.Flightcontrol,
  techs.Render,
  techs.BlitzJS,
  techs.Docker,
  techs.NGINX,
  techs.StoryBook,
  techs.StoryBlok,
  techs.GitHub,
  techs.Husky,
  techs.CICD,
  techs.Figma,
];
